// src/config/keywordSets.js

export const KEYWORD_SETS = {
    dataCollection: [
        // generic collection
        "collect",
        "collection",
        "gather",
        "record",
        "store",
        "information we collect",
        "data we collect",

        // tracking & analytics
        "cookies",
        "cookie",
        "tracking technologies",
        "tracking tools",
        "pixels",
        "web beacons",
        "tags",
        "sdk",
        "analytics",
        "google analytics",
        "mixpanel",
        "segment",
        "page views",

        // device / network
        "ip address",
        "device id",
        "device identifier",
        "advertising id",
        "ad id",
        "idfa",
        "gaid",
        "browser type",
        "browser version",
        "operating system",
        "os version",
        "network provider",
        "mobile carrier",

        // location
        "location data",
        "geolocation",
        "gps",
        "precise location",
        "approximate location",

        // account / profile
        "profile information",
        "contact information",
        "email address",
        "phone number",
        "username",
        "payment information",
        "billing information",
        "demographic information",
        "age",
        "date of birth",

        // biometrics / AI-ish stuff
        "biometric",
        "biometric data",
        "face recognition",
        "facial recognition",
        "fingerprint",
        "voiceprint",
        "iris scan",
        "retina scan",
        "automated decision-making",
        "profiling",
        "personalized recommendations",
    ],

    thirdPartySharing: [
        "third party",
        "third parties",
        "third-party",
        "share",
        "sharing",
        "shared",
        "disclose",
        "disclosure",
        "selling",
        "sell",
        "sold",
        "sale of personal information",
        "data broker",
        "data brokers",
        "partners",
        "business partners",
        "affiliates",
        "subsidiaries",
        "group companies",
        "vendors",
        "service providers",
        "processors",
        "sub-processors",
        "advertisers",
        "ad networks",
        "ad partners",
        "social networks",
        "social media platforms",
        "law enforcement",
        "government authorities",
    ],

    dataRetention: [
        "retain",
        "retention",
        "store",
        "storage",
        "preserve",
        "archive",
        "archival",
        "keep",
        "retention period",
        "storage period",
        "data retention period",
        "for as long as necessary",
        "for as long as needed",
        "for as long as required",
        "for as long as you use",
        "until you delete",
        "until your account is closed",
        "for legal reasons",
        "to comply with legal obligations",
        "backup copies",
        "backups",
        "logs",
        "log files",
    ],

    userRights: [
        "your rights",
        "data subject rights",
        "privacy rights",
        "access your data",
        "right of access",
        "delete your data",
        "erasure",
        "right to erasure",
        "rectify",
        "rectification",
        "correct your data",
        "update your information",
        "object to processing",
        "right to object",
        "restrict processing",
        "restriction of processing",
        "withdraw consent",
        "withdraw your consent",
        "opt out",
        "opt-out",
        "opt in",
        "opt-in",
        "do not sell",
        "do not share",
        "data portability",
        "portable copy",
        "complaint",
        "lodge a complaint",
        "supervisory authority",
        "appeal",
        "appeals process",
        "privacy settings",
        "manage preferences",
        "cookie preferences",
    ],
};
